-- Migration: Insert Variable Pay Guide Document
insert into company_documents (title, category, department, doc_type, description, content_html)
select
  'Variable Pay Incentive System & Role Scorecards Guide',
  'targets',
  null,
  'article',
  'Comprehensive guide to Atelier variable pay calculation formulas, role metric weights, qualification floors, and overachievement ceilings.',
  '<h2>1. Variable Pay Policy & Philosophy</h2><p>Atelier’s variable pay incentive program rewards team members and teams who drive business performance, guest satisfaction, operational hygiene, and efficiency. Each employee has an agreed monthly target pool (e.g. ₹1,500/month), evaluated on a monthly pay period basis (20th to 19th).</p><h2>2. Calculation Methodology</h2><p><strong>Binary Criteria (Hit / Miss):</strong> Full weight (100%) awarded if the target is met or exceeded; 0% if missed.</p><p><strong>Proportional Criteria (Scaled Attainment):</strong> Payout is proportional to achievement (<code>Actual / Target</code>). If performance falls below the qualification <em>Floor</em>, 0% is awarded. Overachievement is rewarded up to the specified <em>Ceiling</em> cap.</p><h2>3. Role-Based Schemes</h2><ul><li><strong>Service — Captain:</strong> 40% Monthly Sales (₹2.6L target, ₹2.2L floor, ₹3.4L ceiling), 20% Named Google Reviews (2 count), 20% Per Customer Average (₹350 target), 10% Grooming (95%), 10% Service Quality Feedback (80%).</li><li><strong>Service — Helpers:</strong> 70% Team Monthly Sales (₹7.8L target, ₹7.0L floor, ₹8.6L ceiling), 20% Grooming (95%), 10% Service Quality Feedback (80%).</li><li><strong>Kitchen Staff:</strong> 30% Food Quality Feedback (80%), 20% Preparation Time (<=20 mins), 20% Wastage Control (<=₹5,000), 20% Kitchen Hygiene (90%), 10% Grooming (95%).</li><li><strong>B2B Sales + Counter:</strong> 40% B2B Revenue (₹20k target, ₹30k ceiling), 20% New B2B Clients (>=1), 20% Item Returns/Debits (<=₹22,000), 10% Credit Recovery, 10% Counter Sales (₹4.5L target).</li><li><strong>Housekeeping:</strong> 60% Daily Cleaning Checklist On-Time Completion (>=80%), 20% Cleanliness Feedback (>=80%), 20% Breakage Control (<=₹2,000).</li><li><strong>Accounting & Cashier:</strong> 50% Cash/Card Reconciliation (<=10% variance), 30% Swiggy/Zomato Delivery Sales (₹6.5L target), 20% GST Timely Filing (0 delays).</li></ul><h2>4. Payout and Payslip Itemization</h2><p>Variable pay is itemized by individual metric on monthly payslips with earned amounts and attainment percentages.</p>'
where not exists (select 1 from company_documents where title = 'Variable Pay Incentive System & Role Scorecards Guide');
